---
- hosts: all
  become: yes
  vars:
    upload_proxy_server: "{{ lookup('env', 'upload_proxy_server') }}"
    target_environment: "{{ 'preprod' if 'preprod' in upload_proxy_server else 'prod' }}"
    ec2_ssl_priv_key: upload-{{ target_environment }}-viasat-io-key.pem
    ec2_ssl_cert: upload-{{ target_environment }}-viasat-io-elb-cert.pem
    ec2_ssl_cert_chain: upload-{{ target_environment }}-viasat-io-cert-chain.pem
    apache_config: "{{ lookup('env', 'apache_config') }}"  # name of .conf.j2 file in templates/

  handlers:
    - name: restart apache
      service:
        name: apache2
        state: restarted

  tasks:
    - name: Install required software packages.
      package:
        name: apache2
        state: present

    - name: Enable proxy modules of apache2
      apache2_module:
        name: "{{ item }}"
        state: present
      with_items:
        - ssl
        - proxy
        - proxy_http
        - proxy_balancer
        - proxy_connect
        - lbmethod_byrequests
      notify: restart apache

    - name: Install certificates.
      copy:
        src: "{{ item }}"
        dest: "/etc/ssl/certs/{{ item }}"
        owner: root
        group: root
        mode: 0444
      with_items:
        - "{{ ec2_ssl_priv_key }}"
        - "{{ ec2_ssl_cert }}"
        - "{{ ec2_ssl_cert_chain }}"

    - name: Update Apache configuration with virtualhost for upload proxy.
      template:
        src: "{{ apache_config }}.conf.j2"
        dest: /etc/apache2/sites-available/upload-proxy.conf
        owner: root
        group: root
        mode: 0644
      notify: restart apache

    - name: Symlink upload proxy virtualhost to sites-enable.
      file:
        src: /etc/apache2/sites-available/upload-proxy.conf
        dest: /etc/apache2/sites-enabled/upload-proxy.conf
        state: link
      notify: restart apache

    - name: Remove the default Apache configuration file.
      file:
        path: /etc/apache2/sites-enabled/000-default.conf
        state: absent
      notify: restart apache
